### ISSUE TITLE
Stormkit Actions/BOT for slack

### ISSUE THREAD

**Issue by ivanlori** [stormkit-io/app-stormkit-io#26]
**Current situation**
we have the slack integration to display information from stormkit to slack

<img width="1062" alt="Screenshot 2020-09-17 at 08 48 00" src="https://user-images.githubusercontent.com/7620920/93430219-9e377580-f8c2-11ea-8be8-d7e032bf7600.png">

**The goal**
To have the possibility to launch commands from slack and trigger an action in stormkit like deploy.
For i.e. from slack we can have a stormkit bot where the user just types `deploy BRANCH NAME` and stormkit launch that deploy.

**Why**
To speed up the deployment process without having stormkit tab open

**Comment by svedova** [comment]
It's been a while since this issue got opened. We now have Outbound Webhooks, which is a more generic solution. As for triggering deploys, we have endpoints where you can trigger deployments. 

If we still want to bring this functionality to our CLI, please open an issue here: https://github.com/stormkit-io/stormkit-cli 🙏
