### ISSUE TITLE
Port configuration for Self hosted deployment

### ISSUE THREAD

**Issue by aymanapatel** [stormkit-io/app-stormkit-io#578]
Wanted to see if we can change Port for Self-hosted version.

**Comment by svedova** [comment]
Thanks for the issue! 

@aymanapatel can you please describe what PORT are you referring to? 

The Stormkit UI or the application hosted through Stormkit (e.g next.js, node.js)?

The UI can be configured through the following ports: 

- `STORMKIT_HTTPS_PORT` 
- `STORMKIT_HTTP_PORT`

But bear in mind that if you configure these ports, the load balancer (should be a layer 4 because SSL needs to be terminated by Stormkit) still needs to serve 80 and 443 and forward the requests to the configured ports.

If you can tell me why you need to change the port I can help you better.

**Comment by aymanapatel** [comment]
Some ports are blocked by Firewall. Hence need to configure port.
